# Secrets Manager placeholders.
#
# Terraform creates the *containers* and never the values. There is no
# aws_secretsmanager_secret_version anywhere in this stack, deliberately:
#
#   - A value in HCL is a value in git (CLAUDE.md §7: no values in git, values files, DAGs or
#     tests). A value passed through a tfvars file is a value in Terraform state and in every plan
#     output.
#   - Values arrive out of band: SSH host and user keys generated by the operator, the webhook HMAC
#     secret generated once, Snowflake key-pairs generated by FND-11's bootstrap, Keycloak
#     credentials generated at deploy time by FND-6's kcadm Job, per-database passwords written by
#     scripts/db/provision_databases.sh.
#
# Consequence to know about: a secret with no version cannot be read. An ExternalSecret referencing
# one stays NotReady, and the pod that needs it will not start. That is the intended failure -- a
# missing credential should stop a deploy, not produce a service running with an empty secret.
#
# recovery_window_in_days = 0 because a 7-30 day window keeps the *name* reserved after deletion,
# which breaks destroy-then-rebuild: the re-apply fails with "already scheduled for deletion".

locals {
  secret_prefix = "${var.project}/${var.env}"

  placeholder_secrets = {
    # --- SFTP (SIM-3, ING-4) ---
    "sftp/host-key" = {
      description = "SSH host private key for the containerized SFTP server. The client's known-hosts pin is derived from it, so replacing it breaks the A§31 verify-host-key step until the pin is updated."
    }
    "sftp/corebank-user-key" = {
      description = "SSH private key the sftp-worker uses to authenticate as the corebank feed user."
    }

    # --- webhook ingestion (SIM-5, ING-6) ---
    "webhook/hmac-secret" = {
      description = "Shared secret for the X-Signature HMAC on POST /v1/webhooks/payments. Verified in addition to the OIDC JWT (A§34, defense in depth), so both the simulator and the receiver read this one value."
    }

    # --- Snowflake service users (FND-11, applied at Phase 6 kickoff) ---
    "snowflake/airflow-private-key" = {
      description = "PKCS#8 private key for the AIRFLOW_SVC Snowflake user (key-pair auth; no passwords anywhere in Snowflake)."
    }
    "snowflake/dbt-private-key" = {
      description = "PKCS#8 private key for the DBT_SVC Snowflake user."
    }
    "snowflake/dbt-ci-private-key" = {
      description = "PKCS#8 private key for the DBT_CI_SVC Snowflake user, which is scoped to ANALYTICS_CI."
    }

    # --- observability (FND-9) ---
    "grafana/admin" = {
      description = "Grafana admin credentials, consumed by kube-prometheus-stack through an ExternalSecret."
    }

    # --- identity: Keycloak on EKS (FND-6, supersedes Cognito) ---
    "keycloak/admin" = {
      description = "Keycloak bootstrap admin credentials for the colx realm. Consumed by the Keycloak deployment through an ExternalSecret; also what the kcadm.sh Job authenticates with to set client secrets."
    }
    "keycloak/client-platform-services" = {
      description = "Client credentials for the Keycloak `platform-services` M2M client (all service scopes). Written by FND-6's kcadm Job after realm import -- never present in the realm JSON, which is committed."
    }
    "keycloak/client-simulator" = {
      description = "Client credentials for the Keycloak `simulator` M2M client (webhook:write only), used by the payment webhook simulator."
    }
  }
}

resource "aws_secretsmanager_secret" "placeholders" {
  for_each = local.placeholder_secrets

  name        = "${local.secret_prefix}/${each.key}"
  description = each.value.description
  kms_key_id  = module.kms.key_arns["secrets"]

  recovery_window_in_days = var.secret_recovery_window_days

  tags = {
    Name = "${local.secret_prefix}/${each.key}"
  }
}
