// Package postgres is the platform's only path to Postgres: one pool per
// service, one transaction helper, one migration runner, one readiness probe.
//
// The shape follows from ADR-0003 (a database per service on one shared RDS
// instance) and CLAUDE.md §3 (sqlc + pgx/v5, goose migrations embedded, no ORM
// and no query builder):
//
//   - [Connect] builds a *pgxpool.Pool with explicit caps and OpenTelemetry
//     instrumentation. A service never constructs a pool itself, so every
//     service's query spans, pool metrics and timeouts look the same in Grafana.
//   - [WithTx] is the transaction boundary. Business effects and their outbox
//     rows (LIB-C) commit together or not at all, which is the whole reliability
//     argument in ADR-0004.
//   - [Migrate] applies embedded goose migrations under a Postgres session
//     advisory lock, so N replicas of a Deployment rolling at once cannot race.
//   - [ReadyCheck] is the /readyz probe. Liveness deliberately does not touch
//     the database (see platform/health).
//
// Nothing here knows what a case or a payment is. Queries are generated by sqlc
// in the owning service and take a pgx-compatible executor, so this package
// exposes no query API of its own.
package postgres

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"time"

	"github.com/exaring/otelpgx"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/canhtoanptit/collection-platform/platform/health"
)

// Pool caps and timeouts. They are defaults, not policy: every one is an env
// var on [Config] so a heavy consumer can be tuned without a code change.
const (
	// defaultMaxConns is deliberately modest. Around a dozen services share one
	// db.t4g.small (ADR-0003), whose max_connections is in the low hundreds, so
	// a per-service pool of 10 leaves headroom for migrations, psql sessions and
	// the CDC connector. Raise it for a service that measurably saturates it —
	// after checking the instance-wide budget, not before.
	defaultMaxConns = 10
	// defaultMinConns keeps a warm connection so the first request after an idle
	// period does not pay TLS plus authentication.
	defaultMinConns = 1
	// defaultMaxConnLifetime recycles connections so a failover or a parameter
	// change is picked up without a restart.
	defaultMaxConnLifetime = 30 * time.Minute
	defaultMaxConnIdleTime = 5 * time.Minute
	defaultConnectTimeout  = 5 * time.Second
	// defaultStatementTimeout is the backstop against a runaway query pinning a
	// pool connection forever. It is server-side, so it also applies to a query
	// whose client context was leaked.
	defaultStatementTimeout = 30 * time.Second
)

// Config is the Postgres configuration a service embeds in its own config
// struct:
//
//	type Config struct {
//	    config.Base
//	    postgres.Config
//	}
//
// URL binds the same DATABASE_URL as config.Base.DatabaseURL — env parsing is
// read-only, so both fields receive the value and neither is authoritative over
// the other. Embed this one when the service actually opens a pool; the Base
// field exists for deployables (a CronJob, a probe) that only need to pass the
// DSN somewhere else.
type Config struct {
	// URL is the service's own database DSN, in either libpq keyword form or
	// postgres:// URL form. One database per service: no service ever opens
	// another service's (CLAUDE.md §7).
	URL string `env:"DATABASE_URL,required"`

	// MaxConns caps the pool. See defaultMaxConns for why 10.
	MaxConns int32 `env:"DATABASE_MAX_CONNS" envDefault:"10"`
	// MinConns is the number of connections kept open while idle. Zero means the
	// default; a negative value keeps none warm.
	MinConns int32 `env:"DATABASE_MIN_CONNS" envDefault:"1"`

	// MaxConnLifetime retires a connection this long after it was opened.
	MaxConnLifetime time.Duration `env:"DATABASE_MAX_CONN_LIFETIME" envDefault:"30m"`
	// MaxConnIdleTime closes a connection idle for this long.
	MaxConnIdleTime time.Duration `env:"DATABASE_MAX_CONN_IDLE_TIME" envDefault:"5m"`

	// ConnectTimeout bounds a single connection attempt (DNS, TCP, TLS, auth).
	ConnectTimeout time.Duration `env:"DATABASE_CONNECT_TIMEOUT" envDefault:"5s"`
	// StatementTimeout is applied server-side as statement_timeout on every
	// session in the pool. Zero means the default; a *negative* value disables
	// it altogether, which is not recommended — a query with no server-side
	// bound outlives the request that asked for it and keeps its locks.
	StatementTimeout time.Duration `env:"DATABASE_STATEMENT_TIMEOUT" envDefault:"30s"`

	// ApplicationName is reported in pg_stat_activity and in RDS Performance
	// Insights. Set it to the service name — when a lock investigation shows
	// "unnamed", the next question is unanswerable.
	ApplicationName string `env:"DATABASE_APPLICATION_NAME"`
}

// Pinger is the part of a pool [ReadyCheck] needs. *pgxpool.Pool satisfies it;
// so does *pgx.Conn, and so does a fake in a test.
type Pinger interface {
	Ping(ctx context.Context) error
}

// Connect opens the pool and verifies it before returning.
//
// The pool is instrumented with exaring/otelpgx, so every query, batch,
// CopyFrom and connection acquisition is a span with the standard database
// attributes. Query *parameters* are never recorded — otelpgx only includes them
// behind an explicit option, and a parameter is exactly where a customer's name
// or IBAN would be (security/masking matrix).
//
// A failure here must abort startup: a service that starts without its database
// only fails later, in front of a caller (the platform/config rule, applied to
// the dependency rather than the variable).
func Connect(ctx context.Context, cfg Config) (*pgxpool.Pool, error) {
	poolCfg, err := buildPoolConfig(cfg)
	if err != nil {
		return nil, err
	}

	pool, err := pgxpool.NewWithConfig(ctx, poolCfg)
	if err != nil {
		return nil, fmt.Errorf("creating the Postgres pool for %s: %w", poolCfg.ConnConfig.Database, err)
	}

	// NewWithConfig is lazy — it does not dial. Ping proves the DSN, the
	// credentials, the network path and the TLS settings now, at startup, rather
	// than on the first request.
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("connecting to Postgres database %s at %s: %w",
			poolCfg.ConnConfig.Database, poolCfg.ConnConfig.Host, err)
	}
	return pool, nil
}

// buildPoolConfig turns a Config into a pgxpool.Config. It is separate from
// Connect so the mapping is unit-testable without a server.
func buildPoolConfig(cfg Config) (*pgxpool.Config, error) {
	if cfg.URL == "" {
		return nil, errors.New("connecting to Postgres: no DATABASE_URL configured")
	}

	poolCfg, err := pgxpool.ParseConfig(cfg.URL)
	if err != nil {
		// The DSN can carry a password. ParseConfig's error does not echo the
		// input, and neither does this wrap.
		return nil, fmt.Errorf("parsing the Postgres DSN: %w", err)
	}

	// Caps from Config win over pool_* parameters in the DSN: the deployment's
	// environment is the one place a pool size is configured, and a DSN that
	// disagreed would be invisible in `kubectl describe`.
	// Zero means "unset, use the default"; a negative MinConns means "explicitly
	// keep nothing warm". Both caps follow the same rule so neither has a
	// surprising fallback.
	if cfg.MaxConns > 0 {
		poolCfg.MaxConns = cfg.MaxConns
	} else {
		poolCfg.MaxConns = defaultMaxConns
	}
	switch {
	case cfg.MinConns > 0:
		poolCfg.MinConns = cfg.MinConns
	case cfg.MinConns == 0:
		poolCfg.MinConns = defaultMinConns
	default:
		poolCfg.MinConns = 0
	}
	if poolCfg.MinConns > poolCfg.MaxConns {
		return nil, fmt.Errorf("configuring the Postgres pool: MinConns %d exceeds MaxConns %d",
			poolCfg.MinConns, poolCfg.MaxConns)
	}

	poolCfg.MaxConnLifetime = orDefault(cfg.MaxConnLifetime, defaultMaxConnLifetime)
	poolCfg.MaxConnIdleTime = orDefault(cfg.MaxConnIdleTime, defaultMaxConnIdleTime)
	poolCfg.ConnConfig.ConnectTimeout = orDefault(cfg.ConnectTimeout, defaultConnectTimeout)

	// Runtime parameters are sent on every new session in the pool, so they
	// survive connection recycling and cannot be forgotten by a caller.
	// Zero means "unset, use the default"; only a negative value opts out.
	if timeout := cfg.StatementTimeout; timeout >= 0 {
		if timeout == 0 {
			timeout = defaultStatementTimeout
		}
		poolCfg.ConnConfig.RuntimeParams["statement_timeout"] = strconv.FormatInt(timeout.Milliseconds(), 10)
	}
	if cfg.ApplicationName != "" {
		poolCfg.ConnConfig.RuntimeParams["application_name"] = cfg.ApplicationName
	}

	poolCfg.ConnConfig.Tracer = otelpgx.NewTracer(
		// The span name is the SQL statement, trimmed to its first line, which
		// keeps sqlc's named queries readable without turning every parameter
		// into span-name cardinality.
		otelpgx.WithTrimSQLInSpanName(),
	)
	return poolCfg, nil
}

// orDefault returns d when v is zero or negative.
func orDefault(v, d time.Duration) time.Duration {
	if v <= 0 {
		return d
	}
	return v
}

// ReadyCheck reports Postgres as a readiness dependency.
//
// The probe is a Ping — a round trip on a pooled connection — because that is
// what "can this pod serve a request" means. It deliberately runs no query:
// `SELECT 1` against a table would turn a permissions change into a readiness
// outage, and a heavier probe on every poll is a self-inflicted load.
//
// The check fails when the server is unreachable and when the pool has been
// closed. Both must remove the pod from the Service; neither should restart it,
// which is why this is a readiness probe and not a liveness one.
func ReadyCheck(p Pinger) health.Check {
	return health.Check{
		Name: "postgres",
		Probe: func(ctx context.Context) error {
			if p == nil {
				return errors.New("no pool configured")
			}
			if err := p.Ping(ctx); err != nil {
				return fmt.Errorf("pinging Postgres: %w", err)
			}
			return nil
		},
	}
}
